export const ACCOUNT = {
    REGISTER : "REGISTER_MEMBER",
    USERDATA : "USER_DATA"
}
export const BEER = {
    BRANDS : "BRANDS",
    MODELS_OF_BRAND : "MODELS_OF_BRAND",
    LIST : "LIST",
    SEARCH_ONE : "SEARCH_ONE",
    SELECTED : "SELECTED",
    TRIED : "TRIED",
    CATEGORY : "CATEGORY",
    COMPANY : "COMPANY"
}
export const SHOP = {
    NAME : "NAME",
    INFO : "INFO",
    SELECTION : "SELECTION"
}
export const COUNTRY = {
    NAME_LIST_FRENCH : "NAME_LIST_FRENCH"
}
export const DASHBOARD = {
    MENU : "MENU",
    MENU_SELECTED : "MENU_SELECTED"
}

export const ACTIONS = {
    MENUDASHBOARD : "MENU_DASHBOARD",

    REDIRECT_TO_PAGE : "REDIRECT_TO_PAGE"
}
    